FROM --platform=amd64 nginx:bookworm

RUN apt update && apt dist-upgrade -y
RUN apt install -y git composer php php-cli php-opcache php-mysql php-zip php-gd php-mbstring php-curl php-xml

RUN  useradd -ms /bin/bash deming
RUN mkdir -p /var/www/deming 
COPY deming.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www/deming

RUN git clone https://www.github.com/dbarzin/deming .
RUN mkdir -p storage/framework/views && mkdir -p storage/framework/cache && mkdir -p storage/framework/sessions && mkdir -p bootstrap/cache
RUN chmod -R 775 /var/www/deming/storage && chown -R www-data:www-data /var/www/deming
RUN composer install
RUN php artisan vendor:publish --all

RUN cp .env.example .env
RUN sed -i 's/DB_HOST=127\.0\.0\.1/DB_HOST=mysql/' .env

COPY entrypoint.sh /opt/entrypoint.sh
RUN chmod u+x /opt/entrypoint.sh

EXPOSE 80

ENTRYPOINT "/opt/entrypoint.sh"